### ISSUE TITLE
3.5‘’ incorrect touch

### ISSUE THREAD

**Issue by JesonWang09** [goodtft/LCD-show#106]
my 3.5'' screen on Raspbian official mirror, but it got incorrect display.
The X-axis and the Y-axis have opposite information.
such as, when i touch right side of the screen, but the cursor appears at the top of the screen.
What can I do to solve this problem?

**Comment by Jason0416** [comment]
使用Raspberrypi Host name安装

**Comment by JesonWang09** [comment]
> 使用Raspberrypi Host name安装

我用的默认的pi用户通过sudo 提权安装的，和你说的安装方式有什么区别吗

**Comment by saholman** [comment]
I'm having this same issue. Is this a hardware issue or a software issue?

**Comment by saholman** [comment]
This solved my issue: https://github.com/swkim01/waveshare-dtoverlays#touch-calibration

I simply added Option "TransformationMatrix" "0 -1 1 1 0 0 0 0 1" to /etc/X11/xorg.conf.d/99-calibration.conf to rotate touch 90 degrees to the left.

**Comment by rimeno** [comment]
Same problem, solved by @saholman comment. Thanks

**Comment by JesonWang09** [comment]
yeah， @saholman ‘s solution is effective. tks!
