### ISSUE TITLE
Screen brightness

### ISSUE THREAD

**Issue by fpdrozd** [goodtft/LCD-show#127]
Hi, I have [this](https://cdn.sparkfun.com//assets/parts/1/3/0/2/5/14776-LCD_Touchscreen_HAT_for_Raspberry_Pi_-_TFT_3.5in.__480x320_-05.jpg) 3.5" tft screen. Is there any way to decrease its brightness?

**Comment by KrzysztofKarol** [comment]
@fpdrozd That's not possible to solve it software way:
https://www.raspberrypi.org/forums/viewtopic.php?t=149887

**Comment by fpdrozd** [comment]
@KrzysztofKarol That's what I was afraid of. But I'll try the transistor way, dziękuję :)
