### ISSUE TITLE
for me, the 3.5 inch panel does not work

### ISSUE THREAD

**Issue by CuzImBisonratte** [goodtft/LCD-show#135]
I entered the first command and then I was told that I should log in, must I log in with my github data? or did I do something wrong?

**Comment by CuzImBisonratte** [comment]
I have entered the commands now it went. But in the last command (sudo ./LCD35-show) I do not have the necessary permissions. Is there any other command, even if it is more complicated?

**Comment by goodtft** [comment]
something wrong with you system.
try use Raspbian from https://www.raspberrypi.org/downloads/

If you have difficulty installing the driver, or if you still can't use the display properly after installing the driver,
Please Try our Configned images for tested.
Just need download and write the image into the Micro SD card. DO NOT need any driver installation steps.
see our wiki:
http://www.lcdwiki.com/Main_Page

2019-05-05 

goodtft 



发件人：CuzImBisonratte <notifications@github.com>
发送时间：2019-05-03 00:48
主题：Re: [goodtft/LCD-show] for me, the 3.5 inch panel does not work (#135)
收件人："goodtft/LCD-show"<LCD-show@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

I have entered the commands now it went. But in the last command (sudo ./LCD35-show) I do not have the necessary permissions. Is there any other command, even if it is more complicated?

**Comment by CuzImBisonratte** [comment]
I tried it again after a day, now everything works and I am very happy. Thank you for this great product goodtft.
