### ISSUE TITLE
Siwtch off 3.5 inch Screen

### ISSUE THREAD

**Issue by xDavexe** [goodtft/LCD-show#141]
I bought a 3.5 inch Display and this repo works fine, but I like to know if it is impossible to switch off display in running-time. 
Before I make this question I tried with these options:
1. Change /etc/X11/xorg.conf.d/99-calibration.conf, I tried to put the "setting up DPMS" in Xorg file like this [https://wiki.archlinux.org/index.php/Display_Power_Management_Signaling](url) with no good results
2. Disable SPI interface with raspi-config with white screen as result
3. Try different options in /boot/config.txt (dtoverlay=options) to change brightness, Ohm levels and disable GPIO pins with negative result
4. Remove brutally the display and then I re-attach it but with white screen as result
So is there a chance to turn off this dispaly through software?

**Comment by goodtft** [comment]
it does not support to switch off display in running-time
