### ISSUE TITLE
3.5 inch display not working on Kivy fw.

### ISSUE THREAD

**Issue by Eugene-Ch** [goodtft/LCD-show#142]
Hi. The Python script starting without any errors, but on screen nothing happened. Maybe anybody know why?

This is link on aliexpress:
https://www.aliexpress.com/item/3-5-inch-Raspberry-Pi-3-Model-B-Touchscreen-480-320-LCD-Display-Touch-Pen-ABS/32906213419.html?spm=a2g0s.9042311.0.0.3cd44c4dqoussM

**Comment by fschlaef** [comment]
@Eugene-Ch  This script is very poorly coded and erases several system config files without warning, as explained here : #140

I am creating a better alternative here : https://github.com/fschlaef/raspi-lcd/
Would you mind giving it a try ?
