### ISSUE TITLE
3.5" LCD can't  boot on CLI

### ISSUE THREAD

**Issue by sceic** [goodtft/LCD-show#147]
Use LCD_480_320 driver on 2019-06-20-raspbian-buster-lite.img
Then boot,screen fixed on log message.But when i click on something, it appears that the desktop is behind and i can see it briefly before the log comes back...

same issues:
https://github.com/goodtft/LCD-show/issues/107

**Comment by goodtft** [comment]
see this:
https://github.com/lcdwiki/LCD-show-kali

2019-06-29 

goodtft 



发件人：sceic <notifications@github.com>
发送时间：2019-06-28 21:23
主题：[goodtft/LCD-show] 3.5" LCD can't boot on CLI (#147)
收件人："goodtft/LCD-show"<LCD-show@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Use LCD_480_320 driver on 2019-06-20-raspbian-buster-lite.img
Then boot,screen fixed on log message.But when i click on something, it appears that the desktop is behind and i can see it briefly before the log comes back...
same issues:
#107

**Comment by SmUrF3R5** [comment]
same issue with MHS35. I have tried the drive from both repos. I am running latest version of buster
RPI 3 B+

**Comment by goodtft** [comment]
OK,thanks
