### ISSUE TITLE
Disable using of serial

### ISSUE THREAD

**Issue by afxgroup** [goodtft/LCD-show#153]
Hello.
It is possible to disable the use of serial? What the serial is used for? For the touch screen?

**Comment by goodtft** [comment]
I think you can open the serial port.

**Comment by frankdlavoie** [comment]
Every time I install the LCD-show I cannot use serial0 anymore. Any idea how I could force LCD-show to not use the serial0?

**Comment by jay6621** [comment]
#228 follow this to use serial with LCD driver installed
