### ISSUE TITLE
Blank strip on left of screen

### ISSUE THREAD

**Issue by jimjlloyd** [goodtft/LCD-show#157]
I am using the 3.5 inch screen with Raspberry Pi 3B+ - It was working fine then I updated the driver and now I get a blank strip down the left hand edge of the screen - both in 3.5 mode and hdmi. Any ideas?

**Comment by jimjlloyd** [comment]
I think I have fixed it - probably not actually to do with the driver - I think I accidentally created some additional panels - not quite sure what I did, but have removed them and display looks OK

**Comment by goodtft** [comment]
OK,thanks
