### ISSUE TITLE
Moode audio

### ISSUE THREAD

**Issue by jurkodj** [goodtft/LCD-show#158]
Hi, I'm trying to use this 3,5 inch display with Moode audio to display GUI. I have installed drivers, but all I can see on a display is command line. GUI available via web browser is also corrupted after installing display drivers. How can it be fixed? 
thanks

**Comment by RpiVolumio35GPIO** [comment]
http://michael-peeters.blogspot.com/2018/03/

**Comment by jurkodj** [comment]
> 
> 
> http://michael-peeters.blogspot.com/2018/03/

Great, thanks. It works with Volumio, but with Moodeaudio no luck yet.
