### ISSUE TITLE
Inverted colors

### ISSUE THREAD

**Issue by 0x77dev** [goodtft/LCD-show#162]

**Comment by alveola** [comment]
My screen also has inverted colors:
Black <> White
Blue <> Cyan
Green <> Magenta
Red <> Yellow
In the image, you see the same screen sample from vnc (right, correct colors) en the RPi (left, inverted colors)
Does anyone have any hint to solve this?
![rpi-inverted-colors](https://user-images.githubusercontent.com/11578393/67140517-a7a40200-f25b-11e9-85c6-3f3990763580.jpg)

**Comment by 0x77dev** [comment]
I 

> My screen also has inverted colors:
> Black <> White
> Blue <> Cyan
> Green <> Magenta
> Red <> Yellow
> In the image, you see the same screen sample from vnc (right, correct colors) en the RPi (left, inverted colors)
> Does anyone have any hint to solve this?
> ![rpi-inverted-colors](https://user-images.githubusercontent.com/11578393/67140517-a7a40200-f25b-11e9-85c6-3f3990763580.jpg)

I have the same issue

**Comment by goodtft** [comment]
What type of screen do you use? 
How do you install the driver?

**Comment by vishaluae** [comment]
Have the same issue. Using a 3.5" RPI screen.

**Comment by vishaluae** [comment]
@goodtft Is there something that we would need to edit in /boot/config.txt of a Raspberry Pi?

**Comment by mvallerie** [comment]
Same issue here on `MPI3501`.

**Comment by 0x77dev** [comment]
The issue hasn't been updated in a long time.
