### ISSUE TITLE
Support for Rasperri Pi 4

### ISSUE THREAD

**Issue by julianthome** [goodtft/LCD-show#173]
Hello,

I just wanted to ask whether support for Rasperri Pi 4 is planned or whether there is already a tutorial available that explains how to get the TFT diplay to work with a Rasperri Pi 4.

Thanks a lot and kind regards,
  Julian

**Comment by lbussy** [comment]
Julian, using Raspbian Buster dated 09-26 on a Pi 4, no issues following [these instructions](https://github.com/goodtft/LCD-show/issues/166).

**Comment by julianthome** [comment]
Thanks a lot @lbussy 👍
