### ISSUE TITLE
BORDER OF 5 INCH TOUCHSCREEN NOT ACCESSIBLE FOR TOUCH

### ISSUE THREAD

**Issue by perrycannon** [goodtft/LCD-show#18]
There is a 1 cm border around the edge of the touchscreen that cursor will not pass, and is unaccessible for touch. With a keyboard and mouse I am able to move the cursor around the entire screen. The cursor will not move into this area with touch.

**Comment by goodtft** [comment]
The touch needs to be calibrated.
How to calibrate the touch screen

1、	Install Xinput
You need to install the LCD driver first beforce this Step,
follow the document <How to install the LCD driver (En).pdf>
cd /boot
cd LCD-show
sudodpkg -i -B xinput-calibrator_0.7.5-1_armhf.deb
 
2, execute the command of the touch calibration:
DISPLAY=:0.0 xinput_calibrator
The screen will pop up touch calibration display, and now use the touch pen click successively four calibration points to complete the calibration.
New touch parameters would be shown after the calibration, as follows:
 
3, modify the touch parameters after calibration and save
sudonano /etc/X11/xorg.conf.d/99-calibration.conf
As following:
 
Note: Only the resistive touch screen needs to be calibrated, 7”and 10.1”capacitive touch screen do not need to do calibration as this page.
