### ISSUE TITLE
5 inch display touchscreen doesn't work properly

### ISSUE THREAD

**Issue by sezeryalcin** [goodtft/LCD-show#2]
I have 5 inch LCD and graphics works fine. Touchscreen also works but it doesn't work on right and left sides and calibration is off. I kept calibrating several times and it doesn't work.
This is using raspbian jessie, latest image.

**Comment by goodtft** [comment]
if you have try calibration many times, mabe it's a Hardware problem.

**Comment by goodtft** [comment]
if you have try calibration many times, mabe it's a Hardware problem.
