### ISSUE TITLE
End Kernel Panic

### ISSUE THREAD

**Issue by zwarburg** [goodtft/LCD-show#21]
I followed the exact instructions on the main page and it crashed my device. I now get:

```
End kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(179,6)
```

**Comment by inakiuy** [comment]
this post will help you
https://github.com/goodtft/LCD-show/issues/9

> I had some trouble.
> The installation script not consider the noobs partition schema.
> In the file usr/cmdline.txt i had substitute root=/dev/mmcblk0p2 with /dev/mmcblk0pX where X is the partition number of root created by noobs ( in my case is 7). To check i was start rpi in rescue mode.(shift key on boot). I'm sorry for my english.

**Comment by zwarburg** [comment]
@inakiuy Nope didn't help. Tried every value for `x` from 1-9. Nothing works. This destroyed my machine.

**Comment by kb7453** [comment]
I don't know how or why, but that worked for me? I just used the number 7 instead of 2 at the end of the root=/dev/mmcblk0p2

**Comment by randomer666** [comment]
Solution above worked for me as well, thank you @kb7453

**Comment by anandkulkarni** [comment]
Confirming that this works.

**Comment by mpierre0220** [comment]
This works for me. Just booted in recovery mode, (Shift key on the Pi  flash screen) changed root=/dev/mmcblk0p2 to root=/dev/mmcblk0p7 in cmdline.txt, rebooted and everything worked fine. This issue is a life saver.

**Comment by lavolp3** [comment]
I just wrote a commit to get rid of the issue by copying another
cmdline.txt into boot when NOOBS is used

Am 26.10.2017 12:22 schrieb "Marc-Arthur Pierre-Louis" <
notifications@github.com>:

**Comment by mpierre0220** [comment]
Thanks @lavolp3. So if someone clones the repo again and runs LCDXXX-Show, things will now run fine?
