### ISSUE TITLE
Switch between Touch-Screen and Dual-Monitor

### ISSUE THREAD

**Issue by erythana** [goodtft/LCD-show#211]
Hello!

How can i switch between Touch-Screen and Dual-Monitor? I know that it is not possible to run the touch screen when i want to use a second monitor but i installed the drivers and sometimes i just want to use a second display with mouse and keyboard.
Is there a way to switch between both modes?

**Comment by andres-ss25** [comment]
Hello ! 

You can have the LCD 35 display and an HDMI monitor, to switch between them you must go to the LCD-show folder and run
`sudo ./LCD-hdmi` 
if you want to go back to the LCD35 run 
`sudo ./LCD35-show`
the drawback is that for the second command the system reboot
