### ISSUE TITLE
LCD-show for Arch ARM - additional

### ISSUE THREAD

**Issue by kinggx9** [goodtft/LCD-show#248]
Thank you first, goodtft
This guide is for Arch ARM (waveshare35a):
```
git clone https://github.com/goodtft/LCD-show
cd LCD-show
sudo chmod +x LCD35-show
```
=> Option
`nano LCD35-show
`
=> Edit
`sudo dpkg -i -B ./xserver-xorg-input-evdev_1%3a2.10.6-1+b1_armhf.deb 2> error_output.txt
`
=> Add a # in front of it
`#sudo dpkg -i -B ./xserver-xorg-input-evdev_1%3a2.10.6-1+b1_armhf.deb 2> error_output.txt
`
=> Proceed to install the missing part
`sudo pacman -Sy xf86-input-evdev
`
=> Install
`sudo ./LCD35-show
`
=> Go back to HDMI:
`sudo ./LCD-hdmi
`
I hope goodtft will produce Ach ARM an official version

**Comment by goodtft** [comment]
Thank you for your advice
