### ISSUE TITLE
LCD turns off after boot 

### ISSUE THREAD

**Issue by SrBlank** [goodtft/LCD-show#25]
Im using a 3.5in touch screen and all it displays is the boot sequence then the display turns black any help is appreciated thanks

**Comment by vilmarbfilho** [comment]
I have the same problem. Any solutions?

**Comment by vilmarbfilho** [comment]
I found this tuto https://retropie.org.uk/forum/topic/4157/guide-retropie-3-5-inch-rpi-lcd-v3-0-no-brand/7 and solved my problem.
