### ISSUE TITLE
PI 3 reboot after LCD28-show command

### ISSUE THREAD

**Issue by faisal349** [goodtft/LCD-show#26]
Hi,

I am using waveshare 2.8 inch LCD with PI3. I followed the procedure given in the link below.

https://github.com/goodtft/LCD-show

When I tried to run the **sudo ./LCD28-show** command, my PI got restarted. Everytime I run this command, PI gets restarted. Any ideas?

I am using Raspbian (Jessie-Lite).

Thanks

**Comment by faisal349** [comment]
Please find the attached file too.

![lcd_driver_msg](https://user-images.githubusercontent.com/27730297/27540720-7f6d1a52-5a81-11e7-8b75-68441371c51c.PNG)

**Comment by goodtft** [comment]
Now the Driver do not support the newest version Raspbian-07-05,we will find a way update to support.

**Comment by goodtft** [comment]
working well in latest driver
