### ISSUE TITLE
LibreELEC - no command 'git'

### ISSUE THREAD

**Issue by GarageMan** [goodtft/LCD-show#268]
Hello, dear developers,
I recently bought the 5inch TFT touch for my Raspberry Pi 3B+ running LibreELEC (latest version)
Unfortunately, I cannot install the drivers from github using the command 'git' (due to not available on LE)

I am lost about how to install the driver to activate the touch-functionality of the display.

Can you please be so kind as to support me on this?

Thanks a lot.

.:. lutz

**Comment by pheiduck** [comment]
login into shell via ssh or via hdmi > alt+F3 > login on Shell Prompt and try to install git
sudo apt install git -y

**Comment by GarageMan** [comment]
Thanks, pheiduck. I will try that later today and will note my experiences.

**Comment by GarageMan** [comment]
Unfortunately, that does not work. it is not possible to install on LibreElec - except using a Docker container.

**Comment by MechWarriorZero** [comment]
I too having the same issue, I need the driver installed in LibreELEC
