### ISSUE TITLE
PURPLE  line at left side  on 7’’ standard display, 1024 × 600 capacitive touch screen 

### ISSUE THREAD

**Issue by miozer** [goodtft/LCD-show#28]
have a purple vertical bar of 2-3 pixels on the left side

![purple](https://user-images.githubusercontent.com/30121795/28208755-fdc789cc-6897-11e7-96b2-b7b0cfbe13ad.jpeg)
![purple1](https://user-images.githubusercontent.com/30121795/28208768-0a3e4de4-6898-11e7-8a90-1ca3906f5239.jpeg)

**Comment by goodtft** [comment]
fixed
