### ISSUE TITLE
Kernel error MPI4008 with Kali 2021-64bit raspberry-pi

### ISSUE THREAD

**Issue by blueflygene** [goodtft/LCD-show#292]
After installing MPI 4008 driver getting boot error
"Kernel Panic - No working init found. 

is this driver compatible with 2021 Kali yet ?

**Comment by fabianwgl** [comment]
im getting kernel panic as well using raspbian 64bit

**Comment by blueflygene** [comment]
@fabianwgl @LuxStatera this helped me get up and running with my screen. Thanks a ton to https://github.com/danielcshn
