### ISSUE TITLE
New Rapberry Pi 4 Raspbian Bullseye 32bit with LCD35. No Menu dropdown

### ISSUE THREAD

**Issue by Mandelain17** [goodtft/LCD-show#304]
I have bought a new LCD35 and a RP4. Installed the latest Raspbian. Via HDMI no problems but when i do a ./LCD35-show. Raspbian starts but when i klik (via mouse or touch) the "raspbian" button there is no dropdown. The Terminal and chromium button work. Back to hdmi and everything is fine.

**Comment by Mandelain17** [comment]
If I use another desktop environment than it works. But these are not made for small screens. Please reply or change.

**Comment by pecuenban** [comment]
I have the same problem

**Comment by tesdaburys** [comment]
I had this exact problem with bullseye but I used LCD 35 instead of MHS 35 (I have a touch screen) by mistake. When I ran the correct script it worked no problem. Perhaps you made a similar mistake to me?

**Comment by Mandelain17** [comment]
With the new driver it works. I did use the correct script :)
