### ISSUE TITLE
Compatibility for Raspberry Pi 5

### ISSUE THREAD

**Issue by NoIwantyourcode** [goodtft/LCD-show#356]
I have a 2.8 inch display for my new raspberry pi 5. I tried to use the current version of goodtft for this, However it kept on erroring out is there any solutions to this issue

**Comment by NoIwantyourcode** [comment]
Anyone?

**Comment by dune73** [comment]
Same here with Whadda WPI400 3.5" (using the LCD35-show). Works on Raspberry 3 and 4.

**Comment by NoIwantyourcode** [comment]
Do you know of any sort of hotfix that can be used or a more recent Driver that can be used

**Comment by hikkoiri** [comment]
Would also love to see LCD35 display (320x480) support for the Raspberry Pi 5.
(http://www.lcdwiki.com/3.5inch_RPi_Display)

Is this feature part of the roadmap?

**Comment by NoIwantyourcode** [comment]
I got the 2.8 inch screen working with the Deafult driver

**Comment by adjei7** [comment]
OK, scratch that previous comment of mine. I think they fixed compatibility. Mine now works.

I have the same setup as @hikkoiri, Pi 5 with the 3.5 inch touch screen. However, I was connecting it via HDMI to a larger screen.

On a fresh boot, I turned on x11 via raspi-config, and set it to boot up to GUI. 
After rebooting I following the instructions for installing LCD35-show and bingo! All good.

However, if I boot up with both my screens connected (HDMI and 3.5 inch touch), then the 3.5 acts as a touch pad for the HDMI screen and shows nothing but black screen. If I boot up without the HDMI screen, touch screen works great!

**Comment by NoIwantyourcode** [comment]
Glad that it is working
