### ISSUE TITLE
Issue attempting with Ubuntu Mate 16.04.2 LTS

### ISSUE THREAD

**Issue by Mycorrhizae** [goodtft/LCD-show#4]
Attempting to use your repository to get a Kuman 3.5" touchscreen to work on a Pi3.

Downloaded git and cloned your repository with no issues, but "chmod -R 755 LCD-show" command doesn't do anything. Any ideas?

**Comment by goodtft** [comment]
Hello,in ubuntu linux you need to use sudo,such as:
sudo chmod -R 755 LCD-show
or 
sudo chmod -R 777 LCD-show
try it.
