### ISSUE TITLE
rotate lcd screen and touch 

### ISSUE THREAD

**Issue by Sho0ter** [goodtft/LCD-show#49]
i would like to rotate my 7" lcd screen i did it 
but i have a probeleme with touch screen 
can i find  a solution ?

**Comment by sarah278** [comment]
For the 3.5 TFT following change to /etc/X11/xorg.conf.d/99-calibration.conf did the job:

After 
        Option  "SwapAxes"      "1"
insert
        Option  "InvertX"       "1" 
        Option  "InvertY"       "1"

**Comment by binaryjam** [comment]
I have done this but my touch is still not rotated.

I changed boot/config.txt
    dtoverlay=tft35a:rotate=90

(Although, the screen has always been landscape so this seemed unecessary, or there is other config)

I edited the calibration files and did all three of the above, and variations on them but the touch is always the same, x=y y=x.

**Comment by binaryjam** [comment]
Ok I found a document that seems t work for anyone else with this problem
https://wiki.ubuntu.com/X/InputCoordinateTransformation
