### ISSUE TITLE
Screen rotation witl LCD7C

### ISSUE THREAD

**Issue by Beber7310** [goodtft/LCD-show#5]
Could you please provide a setup to rotate the screen and mouse?

Thanks

**Comment by goodtft** [comment]
If you want  Rotete 90°,cmd:
hdmi_drive=1
hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_cvt 1024 600 60 6 0 0 0
display_rotate=1


and for Rotete 180°:
display_rotate=2 
and for Rotete 270°:
display_rotate=3

**Comment by goodtft** [comment]
If you want  Rotete 90°,cmd:
hdmi_drive=1
hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_cvt 1024 600 60 6 0 0 0
display_rotate=1


and for Rotete 180°:
display_rotate=2 
and for Rotete 270°:
display_rotate=3
