### ISSUE TITLE
7 inch lcd connect to BBB(Beaglebon black)

### ISSUE THREAD

**Issue by rsdca** [goodtft/LCD-show#55]
Hello,
is current driver (touch and hdmi) works with BBB ?
thanks

**Comment by goodtft** [comment]
Yes,Sure.


2017-12-21 

goodtft 



发件人：rsdca <notifications@github.com>
发送时间：2017-12-21 03:14
主题：[goodtft/LCD-show] 7 inch lcd connect to BBB(Beaglebon black) (#55)
收件人："goodtft/LCD-show"<LCD-show@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Hello,
is current driver (touch and hdmi) works with BBB ?
thanks
