### ISSUE TITLE
Backlight

### ISSUE THREAD

**Issue by sasbibic** [goodtft/LCD-show#56]
Is it possible to turn backlight off on 7" 1024 display ?

**Comment by mihamil** [comment]
I am also interested if there is a way to shut off the screen or backlight from the OS.  Please advise.

**Comment by goodtft** [comment]
It have a PowerKEY onboard. it's a way off hardware control. Turn it OFF ,the backlight will be shut off.
It  can not shut off the screen or backlight by the OS software ways.

**Comment by goodtft** [comment]
It have a PowerKEY on board
