### ISSUE TITLE
Raspbian Lite/7 inch type b (800x480) unable to connect to X server

### ISSUE THREAD

**Issue by adsmz** [goodtft/LCD-show#65]
On a Pi 3 running raspbian Lite, I'm unable to use startx after installing the driver for the 800 by 480 7 inch screen. Xorg log: http://ix.io/EMD

**Comment by lavolp3** [comment]
Raspbian lite usually does not have a guide installed. Then startx does not
work.
You could either use raspbian full or install the x server in your lite
installation afterwards, e.g. with apt-get install xserver-xorg lxde

Am 27.01.2018 10:20 nachm. schrieb "adsmz" <notifications@github.com>:

**Comment by adsmz** [comment]
I already had xserver-xorg installed, but removed and installed it again to be sure. It still doesn't work

**Comment by lavolp3** [comment]
To me there seems to be a problem with the fbturbo driver.
Can you check if the script really has copied the 99-fbturbo.conf to /usr/share/X11/xorg.conf.d/99-fbturbo.conf?

Additionally, I would try installing the fbturbo driver as described here:
`https://github.com/ssvb/xf86-video-fbturbo/wiki/Installation`
But I'm not sure why this would be important. Maybe it's missing when you "post-install" the xserver. 
At the moment I'm not even sure why the fbturbo driver is needed at all...

**Comment by adsmz** [comment]
Installing fbturbo as described in that link  worked, thanks

**Comment by doskoi** [comment]
Thanks a lot, my waveshare LCD was work with X, but after install the LCD-show to install touch support.
the X isn't working anymore, after I try to install fbturbo, the X is back with touch support.
