### ISSUE TITLE
LCD7C-show prblems configue touch

### ISSUE THREAD

**Issue by maar1201gh** [goodtft/LCD-show#89]
I did everything described in README but the touch don't give no signal to work.

MR

**Comment by jensfr1** [comment]
I have the same issuee. Screen is working but Touch not. Did you solve it?

**Comment by maar1201gh** [comment]
Yes, finally i solved the problem and it's not on screen, neither on raspbian. It's a problem of power source.

I put 2 usb charger 2.1A connected one to raspberry, another to touch screen et voila....It's working.
