### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by fiz1962** [goodtft/LCD-show#90]
First, thanks for this repo.

I started with a fresh copy of Stretch from 3/13/2018.  Changed the password, expanded the filesystem and cloned LCD-Show.  Ran sudo ./LCD35-show.  All seemed to go ok but all I get is a white screen after rebooting.

I believe I have a Pi B+ and Kedei 3.5" TFT v4.  It works with rpi_35_v4_inch_.rar from http://www.osoyoo.com/driver/.

**Comment by goodtft** [comment]
This LCD Driver DO NOT work on Kedei's LCDs, The PIN-out is not the same.

2018-07-30 

goodtft 



发件人：fiz1962 <notifications@github.com>
发送时间：2018-07-21 23:48
主题：[goodtft/LCD-show] White screen (#90)
收件人："goodtft/LCD-show"<LCD-show@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

First, thanks for this repo.
I started with a fresh copy of Stretch from 3/13/2018. Changed the password, expanded the filesystem and cloned LCD-Show. Ran sudo ./LCD35-show. All seemed to go ok but all I get is a white screen after rebooting.
I believe I have a Pi B+ and Kedei 3.5" TFT v4. It works with rpi_35_v4_inch_.rar from http://www.osoyoo.com/driver/.

**Comment by fiz1962** [comment]
Thanks for the reply.  I keep getting this out of my junk box now and then to play with but maybe it's time for the trash.
