### ISSUE TITLE
Install script deletes and overwrites system files without creating a backup.

### ISSUE THREAD

**Issue by tobizviz** [goodtft/LCD-show#91]
For example, MPI3508-show deletes or overwrites the following files without creating backups and without providing a way to roll back:

> /boot/cmdline.txt
> /boot/config.txt
> /etc/inittab

etc

All custom changes to these files will be erased without warning or without creating a backup.

**Comment by goodtft** [comment]
it's now all changes without backups .
we will thinkabout your suggestion.
2018-07-30 

goodtft 



发件人：tobizviz <notifications@github.com>
发送时间：2018-07-25 08:40
主题：[goodtft/LCD-show] Install script deletes and overwrites system files without creating a backup. (#91)
收件人："goodtft/LCD-show"<LCD-show@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

For example, MPI3508-show deletes or overwrites the following files without creating backups and without providing a way to roll back:
/boot/cmdline.txt
/boot/config.txt
/etc/inittab
etc
All custom changes to these files will be erased without warning or without creating a backup.

**Comment by mtraves** [comment]
Are there any plans to correct this behaviour?  A workaround?

**Comment by goodtft** [comment]
see this:
https://github.com/lcdwiki/LCD-show
